baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Resume"
    author = "Jason Dude"
    description = "Website title"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Jason Dude"
		tagline = "Exercise Specialist"
		location = "Salt Lake City, UT"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/jason-dude-b33a2279/"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/JasonDude16"
            title = "GitHub"
	    	[[params.social.list]]
            class = "fab"
            icon = "fa-youtube"
            url = "https://www.youtube.com/channel/UCuo8bY6ao3xjakM8viVCBcQ/videos"
            title = "YouTube"
        [[params.social.list]]
            class = "fab"
            icon = "fa-r-project"
            url = "https://rpubs.com/JasonDude16"
            title = "RPubs"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "certificate"
    [[params.showInAccordion]]
        item = "hobby"
        
    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = """\
          Detail-oriented problem solver studying Kinesiology with an emphasis \
          in cognitive and motor neuroscience and a focus on analytics. Skilled \
          in exercise physiology, neuromechanics, \
          research and writing, and statistical analysis with various software. \
          \n \
          \n \
          Passionate about applying my domain \
          knowledge of Kinesiology to produce data-driven solutions and \
          insights, especially in the areas of clinical informatics \
          and sport performance. \
          """

    # Experience section
    [params.experience]
        title = "Experience"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Masters Student"
            dates = "Aug. 2019 - *Present*"
            link = "https://www.utah.edu/"
            company = "University of Utah"
            details = """\
              * Gained experience with IMUs, EMG, EEG, force plates, and motion capture \n \
              * Wrote MATLAB scripts for signal processing and inverse dynamics analysis \n \
              * Statistically analyzed large datasets in R using GLM and GLMM frameworks \n \
              * Performed data validation, cleaning, wrangling, visualizaiton, and modeling \n \
              * Studied sport performance topics, such as talent identification and development, \
              game intelligence, and practice spacing and consolidation. \
              """
              
        [[params.experience.list]]
            position = "Exercise Specialist (Part-time)"
            dates = "Jan. 2019 - *Present*"
            link = "https://healthcare.utah.edu/"
            company = "University of Utah Health"
            details = """\
              * Designs, supervises, and evaluates exercise therapy programs \n \
              * Performs graded exercise tests with a 12 lead ECG \n \
              * Performs orientations and patient education sessions \n \
              * Reviews and charts on patient's electronic medical records in Epic \
              """
            
        [[params.experience.list]]
            position = "Research Assistant—Physical Activity Research Lab (Part-time)"
            dates = "Fall 2018 - Fall 2019"
            link = "https://health.utah.edu/health-kinesiology/graduate-programs/physical-activity-well-being"
            company = "University of Utah"
            details = """\
              * Recruitment coordinator for a physical activity research study  \n \
              * Collected and analyzed physiological data from a metabolic cart \n  \
              * Efficiently organized subject data using Excel spreadsheets \
              """
        [[params.experience.list]]
            position = "Volunteer Research Assistant—Human Genetics Lab"
            dates = "Spring 2018 - Winter 2018"
            link = "https://health.utah.edu/health-kinesiology/graduate-programs/physical-activity-well-being"
            company = "University of Utah"
            details = """\
              * Studied the Foxn3 gene and its effects on hepatic glucose utilization  \n \
              * Learned and applied western blotting and PCR protocols \n  \
              * Statistically analyzed collected lab samples in Excel (e.g., t-test) \n  \
              * Demonstrated the ability to quickly learn new skills and solve complex problems \
              """
              
        [[params.experience.list]]
            position = "Exercise Physiology Teaching Assistant"
            dates = "Spring 2017 - Fall 2018"
            link = "https://www.utah.edu/"
            company = "University of Utah"
            details = """\
              * Created comprehenisve exam review content and held review sessions  \n \
              * Clearly and effetively presented complex ideas to a large audience \n \
              * Topics included: neuroendocrinology, bioenergetics and metabolism, \
                and cardiovascular, neuromuscular and respiratory physiology. \
              """
              
        [[params.experience.list]]
            position = "Exercise Physiology Lab Teaching Assistant"
            dates = "Spring 2017 - Fall 2017"
            link = "https://www.utah.edu/"
            company = "University of Utah"
            details = """\
              * Taught students how to use technical lab equipment for data collection \n \
              * Taught students how to perform analyses and write scientific reports \n \
              * Topics included: lactate and ventilatory threshold, VO2max, \
              aerobic and anaerobic power, flexibility, body composition assessments, \
              inertial load and fiber type, and hemodynamic response to exercise. \
              """

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "M.S. in Kinesiology"
            college = "University of Utah"
            dates = "2019 - 2021"
        [[params.education.list]]
            degree = "B.S. in Kinesiology"
            college = "University of Utah"
            dates = "2016 - 2018"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles"]

        [[params.publication.list]]
            title = "What the Modified Rankin Isn't Ranking: Stroke Outcomes Differ by Domain"
            authors = "R Braun, L Heitsch"
            date = "(Accepted)"
            journal = "Journal of Neurology"
            link = "#"
            type = "Journal Articles"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Coursera Assignments"
            url = "https://github.com/JasonDude16/Coursera-Data-Science-Specialization"
            description = """\
              For Coursera's Data Science Specialization by Johns Hopkins University \
              I performed the entire data science pipeline: getting and cleaning data, \
              exploratory analysis, statistics and machine learning, and creating data \
              products. Assignments were completed using R and SQL. \
              """ 
        [[params.project.list]]
            title = "Biomechanical Analysis"
            url = "https://github.com/JasonDude16/Biomechanics-Inverse-Dynamics"
            description = """\
              I wrote MATLAB scripts for data filtering, signal processing, \
              and inverse dynamics analysis of force plate and motion capture data \
              for an advanced biomechanics course at the University of Utah. \
              """
        [[params.project.list]]
            title = "Weight Lifting Exercise Classifcation"
            url = "https://github.com/JasonDude16/Weight-Lifting-Classification"
            description = """\
              I implemented several machine learning \
              models for classifying variations of a weight lifting exercise (a barbell curl). \
              In the RMarkdown file I embedded a simple shiny application to assist with \
              data visualization. \
              """
        [[params.project.list]]
            title = "Cardiovascular Disease Classification"
            url = "https://rpubs.com/JasonDude16/698249"
            description = """\
              I created a logistic regression model for cardiovascular disease \
              classification. I processed the data, performed exploratory analysis \
              and feature engineering, assessed model assumptions and fit, and created \
              a confusion matrix to assess accuracy on the train and test sets. \
              """
        [[params.project.list]]
            title = "Statistical Analysis Guidebook"
            url = "https://github.com/JasonDude16/Statistical-Analysis-Guidebook"
            description = """\
              As a summer project I put together a how-to guidebook for performing \
              various statistical analyses in R. I start off by explaining basic \
              programming concepts, packages and libraries, how to read and write files, \
              and data summarizing and formatting. I then provided examples of how to implement \
              various statistical models from the general linear model framework in R, \
              and in the summer of 2021 I plan on extending this guidebook to include \
              generalized- and generalized linear mixed model frameworks. 
              """
        [[params.project.list]]
            title = "Interactive Alluvial Plot with Tableau"
            url = "https://www.youtube.com/watch?v=sl_7p1Ze8o0&t=0s"
            description = """\
              I collaborated with researchers at the University of Maryland to create \
              an interactive alluvial plot of stroke outcomes data. The visualization \
              was included in a research article (Braun, 2020) submitted to the Journal \
              of Neurology titled *What the Modified Rankin Isn't Ranking: Stroke Outcomes \
              Differ by Domain*. The link above is a YouTube video of me describing \
              the visualization. \
              """
              
    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Python"
            skillrating = 75
        [[params.skill.list]]
            skill = "MATLAB/Octave"
            skillrating = 65
        [[params.skill.list]]
            skill = "R & RStudio"
            skillrating = 90
        [[params.skill.list]]
            skill = "Tableau"
            skillrating = 80 
        [[params.skill.list]]
            skill = "AWS Cloud Computing"
            skillrating = 65
        [[params.skill.list]]
            skill = "SQL & Relational Databases"
            skillrating = 70
        [[params.skill.list]]
            skill = "Communication & Presentation"
            skillrating = 95

    [params.certificate]
        title = "Certificates"
        icon = "fas fa-certificate"
        
        [[params.certificate.list]]		
		    certificate = "1. Learning Python | LinkedIn"
        [[params.certificate.list]]		
		    certificate = "2. Data Ingestion with Python | LinkedIn"
        [[params.certificate.list]]		
		    certificate = "3. Python Essential Training | LinkedIn"
        [[params.certificate.list]]		
		    certificate = "4. Python Scientific Stack | LinkedIn"
        [[params.certificate.list]]		
		    certificate = "5. AWS Machine Learning | LinkedIn"
        [[params.certificate.list]]		
		    certificate = "6. Learning Amazon Sagemaker | LinkedIn"
        [[params.certificate.list]]		
		    certificate = "7. Data Science Math Skills | Coursera"
        [[params.certificate.list]]		
		    certificate = "8. Integrating Tableau and R | Coursera"	
        [[params.certificate.list]]		
		    certificate = "9. R Programming: High Volume Data | LinkedIn"
        [[params.certificate.list]]		
		    certificate = "10. JHU Data Science Specialization (R) | Coursera"
		    
    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-bicycle"
		
        [[params.hobby.list]]		
		    hobby = "Skiing"
        [[params.hobby.list]]		
		    hobby = "Hiking"
        [[params.hobby.list]]		
		    hobby = "Gymming"
        [[params.hobby.list]]		
		    hobby = "Mountain Biking"
        [[params.hobby.list]]		
		    hobby = "Pickleballing"
        [[params.hobby.list]]		
		    hobby = "Board Games"
		    